[project]
name = "focus-tracker-lite"
version = "0.1.0"
description = "Minimalist productivity focus timer TUI app with local SQLite storage"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playsound3>=3.2.3",
    "textual>=3.2.0",
]
